/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Handle to an active Agent Assembly session, wrapping the shared
 * [`AssemblyClient`]. The inner `Arc` keeps napi calls cheap and lets the
 * async `disconnect` move a clone onto a blocking task.
 */
export declare class ClientHandle {

}

/**
 * Connect to the `aa-runtime` Unix-domain socket and open a session.
 *
 * Socket resolution, the background IPC thread, and the wire codec are all
 * delegated to `aa-sdk-client`; this shim only validates the argument and
 * wraps the resulting client.
 */
export declare function connect(socketPath: string): Promise<ClientHandle>

/**
 * Shut down the session and join the background IPC thread.
 *
 * Idempotent — delegates to [`AssemblyClient::shutdown`], which blocks on the
 * background-thread join, so it runs on a blocking task to keep the napi async
 * runtime free.
 */
export declare function disconnect(handle: ClientHandle): Promise<void>

/**
 * A policy verdict returned to JS.
 *
 * `decision` is one of `"allow"`, `"deny"`, `"pending"`, `"redact"`; `reason`
 * is the human-readable explanation from the policy engine (or the fail-open
 * note when the runtime did not answer).
 */
export interface PolicyDecision {
  decision: string
  reason: string
}

/**
 * Query the runtime for a policy decision on an action.
 *
 * The JS query object is translated into a `CheckActionRequest` (agent id,
 * action type, and — for tool calls — tool name / source / args) and handed
 * to [`AssemblyClient::query_policy`], which blocks its calling thread for up
 * to 5s waiting on the runtime's `CheckActionResponse`. That blocking call is
 * run on a `spawn_blocking` task — exactly like [`disconnect`] — so the napi
 * async runtime stays free and the **Node event loop is never blocked** while
 * a slow runtime is answering.
 *
 * **Fail-open:** the SDK is advisory, not a security boundary. When the
 * runtime does not return a decision — it is too slow or the connection
 * closed ([`SdkClientError::QueryFailed`]), or it was never reachable so the
 * IPC channel is closed / the session is shut down — this returns a non-deny
 * `"allow"` so a missing or degraded runtime never blocks the agent (the
 * proxy / eBPF layers remain authoritative). Only a genuine local fault
 * (a poisoned lock) surfaces as a typed error.
 */
export declare function queryPolicy(handle: ClientHandle, query: any): Promise<PolicyDecision>

/**
 * Ship a captured event to the runtime.
 *
 * The JS event object is translated to the shared client's
 * `(event_type, details)` shape and forwarded via
 * [`AssemblyClient::report_event`]. Advisory preflight (inside the shared
 * client) may redact locally; the runtime re-scans the event authoritatively
 * regardless.
 */
export declare function sendEvent(handle: ClientHandle, event: any): void
