/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ClientHandle {

}

export declare function connect(socketPath: string): Promise<ClientHandle>

export declare function disconnect(handle: ClientHandle): Promise<void>

export interface PolicyResult {
  denied?: boolean
  pending?: boolean
  reason?: string
}

export declare function queryPolicy(handle: ClientHandle, action: any): Promise<PolicyResult>

export declare function sendEvent(handle: ClientHandle, event: any): void

export declare function socketPath(handle: ClientHandle): string
