#!/usr/bin/env node
// Regenerate TypeScript proto stubs from the sibling agent-assembly checkout.
//
// AAASM-1655 (PR-F of AAASM-1422). Generates only the protos this SDK
// actually consumes today (policy + common). The output lives under
// `src/proto/generated/` and is committed so npm consumers don't need
// `grpc-tools` installed.
//
// Usage:
//   pnpm gen:proto
//   # or with a non-default sibling location:
//   AA_PROTO_DIR=/some/other/agent-assembly/proto pnpm gen:proto
//
// A drift-check CI job (regen + diff) is left as a follow-up hygiene
// sub-task.

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");

// Per memory `project_sibling_repo_ci_pattern`: cross-repo deps use
// sibling-checkout via env vars. Default mirrors the workspace layout
// ($REPO_PARENT/agent-assembly/proto).
const DEFAULT_PROTO_DIR = resolve(REPO_ROOT, "..", "agent-assembly", "proto");

// Only generate the protos the SDK actually consumes. Keeping the set
// tight keeps the committed-stubs diff readable and avoids accidentally
// coupling the SDK to RPCs it doesn't use.
const PROTO_FILES = ["common.proto", "policy.proto"];

const OUTPUT_DIR = resolve(REPO_ROOT, "src", "proto", "generated");

function main() {
  const protoDir = resolve(process.env.AA_PROTO_DIR ?? DEFAULT_PROTO_DIR);
  if (!existsSync(protoDir)) {
    console.error(`error: proto dir ${protoDir} does not exist`);
    console.error("Set AA_PROTO_DIR to the agent-assembly/proto location.");
    process.exit(1);
  }

  mkdirSync(OUTPUT_DIR, { recursive: true });

  const protocBin = resolve(REPO_ROOT, "node_modules/.bin/grpc_tools_node_protoc");
  const tsProtoPlugin = resolve(REPO_ROOT, "node_modules/.bin/protoc-gen-ts_proto");

  const args = [
    `--plugin=protoc-gen-ts_proto=${tsProtoPlugin}`,
    `--ts_proto_out=${OUTPUT_DIR}`,
    // esModuleInterop + outputServices=grpc-js produces an idiomatic
    // grpc-js-compatible client; useExactTypes keeps optional fields strict.
    "--ts_proto_opt=esModuleInterop=true,outputServices=grpc-js,useExactTypes=false,env=node,importSuffix=.js",
    `--proto_path=${protoDir}`,
    ...PROTO_FILES.map((name) => join(protoDir, name)),
  ];

  console.log(`running: ${protocBin} ${args.join(" ")}`);
  const result = spawnSync(protocBin, args, { stdio: "inherit" });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }

  // Drop a marker so consumers know these files are auto-generated.
  for (const file of readdirSync(OUTPUT_DIR)) {
    if (!file.endsWith(".ts")) continue;
    const path = join(OUTPUT_DIR, file);
    const original = readFileSync(path, "utf8");
    if (original.startsWith("// AUTO-GENERATED")) continue;
    writeFileSync(
      path,
      `// AUTO-GENERATED by scripts/gen-proto.mjs from ../agent-assembly/proto/. Do not edit by hand.\n${original}`,
    );
  }
}

main();
