import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// AAASM-4514: the quick-start section 3 framework tabs are generated into a
// bounded block in docs/02-quick-start/index.md from the vendored snippet
// manifest under metadata/quickstart-snippets/. These tests assert on the
// committed, rendered block (the shipped output) rather than importing the
// generator module: the generator's own regenerate-and-git-diff drift check
// exercises the generation path, and asserting on the output keeps this suite
// free of the generator's fenced-code string literals.

// The three-backtick code-fence marker, built from a unicode escape so the
// source carries no literal backtick at all (keeps the suite trivially portable
// across toolchains that tokenize source before running it).
const FENCE = "\u0060".repeat(3);

const docPath = path.resolve(
  fileURLToPath(import.meta.url),
  "../../..",
  "docs/02-quick-start/index.md"
);

const readmePath = path.resolve(
  fileURLToPath(import.meta.url),
  "../../..",
  "README.md"
);

function tabBlock(): string {
  const doc = readFileSync(docPath, "utf8");
  const match = doc.match(
    /BEGIN GENERATED: quickstart-framework-tabs[\s\S]*?END GENERATED: quickstart-framework-tabs/
  );
  if (match === null) {
    throw new Error("quickstart-framework-tabs generated block not found");
  }
  return match[0];
}

// AAASM-4919: the README "Project status" release-line prose used to hand-carry
// `0.0.1-rc.x` outside any generated block, so it could silently drift from the
// package.json version / metadata dist-tag SoT. It now lives in a `release-line`
// bounded block; these tests pin the shipped block and, critically, assert the
// release-line literal appears ONLY inside a generated block so a future
// hand-edit reintroducing an orphan literal is caught here as well as by the CI
// regenerate-and-git-diff drift gate.
function readmeBlock(id: string): string {
  const readme = readFileSync(readmePath, "utf8");
  const match = readme.match(
    new RegExp(`BEGIN GENERATED: ${id}[\\s\\S]*?END GENERATED: ${id}`)
  );
  if (match === null) {
    throw new Error(`${id} generated block not found in README.md`);
  }
  return match[0];
}

describe("README release-line prose (generated block)", () => {
  it("renders the current release line and dist-tag inside the block", () => {
    const block = readmeBlock("release-line");
    expect(block).toContain("The current release line is `0.0.1-rc.x`");
    expect(block).toContain("`rc` dist-tag");
  });

  it("carries the DO NOT EDIT generator banner", () => {
    expect(readmeBlock("release-line")).toContain(
      "GENERATED BY scripts/generate-docs-metadata.mjs"
    );
  });

  it("keeps the `0.0.1-rc.x` release-line literal only inside a generated block", () => {
    const readme = readFileSync(readmePath, "utf8");
    // Strip every generated block, then assert the release-line literal is gone
    // — any remaining occurrence is an un-gated orphan literal (ADR 0013).
    const withoutGenerated = readme.replace(
      /BEGIN GENERATED:[\s\S]*?END GENERATED: [\w-]+/g,
      ""
    );
    expect(withoutGenerated).not.toContain("0.0.1-rc.x");
  });
});

describe("quickstart framework tabs (generated doc block)", () => {
  it("renders a tab for every Node framework", () => {
    const block = tabBlock();
    for (const label of [
      "LangChain.js",
      "Custom (no framework)",
      "OpenAI (Node)",
      "Vercel AI SDK",
      "LangGraph.js",
      "Mastra"
    ]) {
      expect(block).toContain(label);
    }
  });

  it("orders validated frameworks before experimental ones", () => {
    const block = tabBlock();
    expect(block.indexOf("langchain-js-basic-agent")).toBeLessThan(
      block.indexOf("langgraph-js")
    );
    expect(block.indexOf("custom-tool-policy")).toBeLessThan(
      block.indexOf("mastra")
    );
  });

  it("defaults to LangChain.js and suffixes experimental tab labels", () => {
    const block = tabBlock();
    expect(block).toContain('label="LangChain.js" default');
    expect(block).toContain('label="Mastra (Experimental)"');
    expect(block).toContain('label="LangGraph.js (Experimental)"');
    // Validated frameworks keep a plain label (no suffix).
    expect(block).not.toContain("LangChain.js (Experimental)");
  });

  it("embeds each framework's snippet in a ts code fence", () => {
    const block = tabBlock();
    expect(block).toContain(FENCE + "ts");
    for (const agentId of [
      "langchain-js-example-agent",
      "custom-tool-policy-agent",
      "openai-node-example-agent",
      "vercel-ai-example-agent",
      "langgraph-js-example-agent",
      "mastra-example-agent"
    ]) {
      expect(block).toContain(agentId);
    }
  });
});
